### ISSUE TITLE
LCD Library not declared in this scope 

### ISSUE THREAD

**Issue by M0rxira1** [Dominik-Workshop/Linear_power_supply#1]
Can u provide the link to the especific library you used in the project 
thank you 

off topic question 
   How is this voltage reaple of the supply in varius loads 0, 1 and all the way to 10A and across its voltage range ???

**Comment by Dominik-Workshop** [comment]
As far as I remember I just used the library installed directly in the library manager in Arduino IDE.

The voltage ripple and noise measurements, along with transient response measurements are included in the file: measurements.pdf (in this repository).
